---
functional: # функциональные требования (действия, кот. система должна быть способной выполн-ть)
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional: # нефункциональные требования (св-ва, кот. сис-ма должна демонстр-ть, или огранич-я, кот. она должна собл-ть, не относящ-ся к повед-ю сис-мы)
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit: # неявные требования (могут быть не сформулированы и их необходимо написать самостоятельно)
  - Сайт должен иметь функцию уведомления пользователя при добавлении товара в корзину
  - Пользователь должен иметь возможность подтвердить операцию по оформлению заказа и удалении товаров из корзины
  - Сайт должен иметь раздел "Контакты"
