---
functional: # функциональные требования (действия, кот. система должна быть способной выполн-ть)
  - требование 1
  - требование 2
non-functional: # нефункциональные требования (св-ва, кот. сис-ма должна демонстр-ть, или огранич-я, кот. она должна собл-ть, не относящ-ся к повед-ю сис-мы)
  - требование 3
  - требование 4
implicit: # неявные требования (могут быть не сформулированы и их необходимо написать самостоятельно)
  - требование 5
  - требование 6
